# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x06sensor\"s\n\rEnergyReading\x12\x13\n\x0b\x62uilding_id\x18\x01 \x01(\t\x12\x10\n\x08\x66loor_id\x18\x02 \x01(\t\x12\x17\n\x0f\x63urrent_wattage\x18\x03 \x01(\x01\x12\x0f\n\x07voltage\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"2\n\x0eStreamResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2S\n\x0c\x45nergySensor\x12\x43\n\x10StreamEnergyData\x12\x15.sensor.EnergyReading\x1a\x16.sensor.StreamResponse(\x01\x42\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_ENERGYREADING']._serialized_start=24
  _globals['_ENERGYREADING']._serialized_end=139
  _globals['_STREAMRESPONSE']._serialized_start=141
  _globals['_STREAMRESPONSE']._serialized_end=191
  _globals['_ENERGYSENSOR']._serialized_start=193
  _globals['_ENERGYSENSOR']._serialized_end=276
# @@protoc_insertion_point(module_scope)
