// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: sensor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnergySensor_StreamEnergyData_FullMethodName = "/sensor.EnergySensor/StreamEnergyData"
)

// EnergySensorClient is the client API for EnergySensor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnergySensorClient interface {
	StreamEnergyData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EnergyReading, StreamResponse], error)
}

type energySensorClient struct {
	cc grpc.ClientConnInterface
}

func NewEnergySensorClient(cc grpc.ClientConnInterface) EnergySensorClient {
	return &energySensorClient{cc}
}

func (c *energySensorClient) StreamEnergyData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EnergyReading, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EnergySensor_ServiceDesc.Streams[0], EnergySensor_StreamEnergyData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EnergyReading, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EnergySensor_StreamEnergyDataClient = grpc.ClientStreamingClient[EnergyReading, StreamResponse]

// EnergySensorServer is the server API for EnergySensor service.
// All implementations must embed UnimplementedEnergySensorServer
// for forward compatibility.
type EnergySensorServer interface {
	StreamEnergyData(grpc.ClientStreamingServer[EnergyReading, StreamResponse]) error
	mustEmbedUnimplementedEnergySensorServer()
}

// UnimplementedEnergySensorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnergySensorServer struct{}

func (UnimplementedEnergySensorServer) StreamEnergyData(grpc.ClientStreamingServer[EnergyReading, StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamEnergyData not implemented")
}
func (UnimplementedEnergySensorServer) mustEmbedUnimplementedEnergySensorServer() {}
func (UnimplementedEnergySensorServer) testEmbeddedByValue()                      {}

// UnsafeEnergySensorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnergySensorServer will
// result in compilation errors.
type UnsafeEnergySensorServer interface {
	mustEmbedUnimplementedEnergySensorServer()
}

func RegisterEnergySensorServer(s grpc.ServiceRegistrar, srv EnergySensorServer) {
	// If the following call panics, it indicates UnimplementedEnergySensorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnergySensor_ServiceDesc, srv)
}

func _EnergySensor_StreamEnergyData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EnergySensorServer).StreamEnergyData(&grpc.GenericServerStream[EnergyReading, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EnergySensor_StreamEnergyDataServer = grpc.ClientStreamingServer[EnergyReading, StreamResponse]

// EnergySensor_ServiceDesc is the grpc.ServiceDesc for EnergySensor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnergySensor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sensor.EnergySensor",
	HandlerType: (*EnergySensorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEnergyData",
			Handler:       _EnergySensor_StreamEnergyData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sensor.proto",
}
